name: search_package_one
description: |
  Provides implementations of Linear Search, Binary Search, and Jump Search algorithms.
  Supports lists of integers and strings, returning the index of  target element or -1 if not found.

version: 1.0.1

homepage: https://github.com/Bakhodir95/search_package_use.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  repository: ^3.0.0
  test: ^1.25.8

dev_dependencies:
  lints: ^3.0.0
