name: search_package_one
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo


environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  test: ^1.25.8
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
