name: search_package_one
description: |
  This package provides implementations of common search algorithms including Linear Search, Binary Search, and Jump Search.
  Each search function returns the index of the target element if found, otherwise it returns -1. 

version: 1.0.1

homepage: https://github.com/Bakhodir95/search_package_use.git

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  repository: ^3.0.0
  test: ^1.25.8

dev_dependencies:
  lints: ^3.0.0
